/**
 * MSL Validation Program - Compare with MATLAB results
 *
 * This program reads test data generated by MATLAB and compares
 * MSL's FFT and Filter results with MATLAB's reference results.
 */

#include "test.hpp"

#include <cmath>
#include <iomanip>
#include <iostream>
#include <numbers>
#include <vector>
#include "fft/fft.hpp"
#include "signal/filter_apply.hpp"
#include "signal/filter_design.hpp"

#include "helper.hpp"

using namespace msl;

// ============================================================================
// Test 1: FFT - Single Frequency
// ============================================================================

void test1_fft_single_frequency()
{
    std::cout << "\n========================================\n";
    std::cout << "Test 1: FFT - Single Frequency\n";
    std::cout << "========================================\n\n";

    // Parameters (must match MATLAB script)
    const size_t n = 128;
    const double fs = 100.0;
    const double f0 = 5.0;

    // Generate signal
    std::vector<double> signal(n);
    for (size_t i = 0; i < n; ++i)
    {
        double t = i / fs;
        signal[i] = std::sin(2.0 * std::numbers::pi * f0 * t);
    }

    // Compute FFT
    auto fft_result = fft::fft(signal);

    // Extract magnitude
    std::vector<double> magnitude(fft_result.size());
    for (size_t i = 0; i < fft_result.size(); ++i)
    {
        magnitude[i] = std::abs(fft_result[i]);
    }

    // Load MATLAB reference
    try
    {
        auto matlab_magnitude =
            read_csv("msl_validation_data/test1_fft_magnitude.csv");

        // Compare (only frequency values, skip magnitude column in CSV)
        std::vector<double> matlab_mag_only;
        for (size_t i = 1; i < matlab_magnitude.size(); i += 2)
        {
            matlab_mag_only.push_back(matlab_magnitude[i]);
        }

        if (magnitude.size() != matlab_mag_only.size())
        {
            std::cout << "Warning: Size mismatch (MSL: " << magnitude.size()
                      << ", MATLAB: " << matlab_mag_only.size() << ")\n";
        }
        else
        {
            double error = max_abs_error(magnitude, matlab_mag_only);
            print_result("FFT magnitude", error, 1e-10);
        }
    }
    catch (const std::exception &e)
    {
        std::cout << "Could not load MATLAB reference: " << e.what() << "\n";
        std::cout << "Skipping validation (test still ran successfully)\n";
    }

    // Display peak
    size_t peak_idx = 0;
    double peak_val = 0.0;
    for (size_t i = 1; i < magnitude.size(); ++i)
    {
        if (magnitude[i] > peak_val)
        {
            peak_val = magnitude[i];
            peak_idx = i;
        }
    }

    auto freqs = fft::fft_frequencies(n, fs);
    std::cout << "\nMSL Results:\n";
    std::cout << "  Peak magnitude: " << peak_val << " at " << freqs[peak_idx]
              << " Hz\n";
    std::cout << "  Expected: peak at " << f0 << " Hz\n";
}

// ============================================================================
// Test 2: FFT - Multi-frequency
// ============================================================================

void test2_fft_multifrequency()
{
    std::cout << "\n========================================\n";
    std::cout << "Test 2: FFT - Multi-frequency\n";
    std::cout << "========================================\n\n";

    const size_t n = 256;
    const double fs = 100.0;
    std::vector<double> test_freqs = {3.0, 7.0, 15.0};
    std::vector<double> amps = {1.0, 0.5, 0.3};

    // Generate signal
    std::vector<double> signal(n, 0.0);
    for (size_t i = 0; i < n; ++i)
    {
        double t = i / fs;
        for (size_t f = 0; f < test_freqs.size(); ++f)
        {
            signal[i] +=
                amps[f] * std::sin(2.0 * std::numbers::pi * test_freqs[f] * t);
        }
    }

    // Apply Hamming window
    fft::apply_hamming_window(signal);

    // Compute FFT
    auto fft_result = fft::fft(signal);
    auto magnitude = fft::magnitude_spectrum(fft_result);
    auto freqs = fft::fft_frequencies(n, fs);

    // Find peaks
    std::cout << "Detected frequency peaks:\n";
    for (size_t i = 1; i < magnitude.size() - 1; ++i)
    {
        if (magnitude[i] > 10.0 && magnitude[i] > magnitude[i - 1]
            && magnitude[i] > magnitude[i + 1])
        {
            std::cout << "  " << freqs[i] << " Hz (magnitude: " << magnitude[i]
                      << ")\n";
        }
    }
    std::cout << "Expected: 3, 7, 15 Hz\n";
}

// ============================================================================
// Test 3: IFFT Reconstruction
// ============================================================================

void test3_ifft_reconstruction()
{
    std::cout << "\n========================================\n";
    std::cout << "Test 3: IFFT Reconstruction\n";
    std::cout << "========================================\n\n";

    const size_t n = 128;
    const double fs = 100.0;
    const double f0 = 5.0;

    // Generate signal
    std::vector<double> signal(n);
    for (size_t i = 0; i < n; ++i)
    {
        double t = i / fs;
        signal[i] = std::sin(2.0 * std::numbers::pi * f0 * t);
    }

    // FFT -> IFFT
    auto fft_result = fft::fft(signal);
    auto reconstructed = fft::ifft_real(fft_result, n);

    // Compute error
    double error = max_abs_error(signal, reconstructed);

    print_result("IFFT reconstruction", error, 1e-10);
}

// ============================================================================
// Main
// ============================================================================

int test_fft_matlab()
{
    std::cout << "==============================================\n";
    std::cout << "MSL Validation Program\n";
    std::cout << "Comparing with MATLAB Reference Results\n";
    std::cout << "==============================================\n";

    try
    {
        // FFT Tests
        test1_fft_single_frequency();
        test2_fft_multifrequency();
        test3_ifft_reconstruction();

        std::cout << "\n==============================================\n";
        std::cout << "Validation Complete!\n";
        std::cout << "==============================================\n\n";

        std::cout << "Note: If MATLAB reference files are not found,\n";
        std::cout << "      tests will still run and show MSL results.\n";
        std::cout << "      Run the MATLAB script first to generate\n";
        std::cout << "      reference data for full validation.\n";
    }
    catch (const std::exception &e)
    {
        std::cerr << "\nError: " << e.what() << "\n";
        return 1;
    }

    return 0;
}